export enum Actions {
    CREATE_HOLIDAY = "CREATE_HOLIDAY",
    CREATE_GROUP = "CREATE_GROUP",
    UPDATE_INFO = "UPDATE_INFO",
    UPDATE_PASS = "UPDATE_PASS",
    DELETE_HOLIDAY = "DELETE_HOLIDAY",
    DELETE_GROUP = "DELETE_GROUP",
    DELETE_ACCOUNT = "DELETE_ACCOUNT",
    GETOUT_GROUP = "GETOUT_GROUP",
}
